### ISSUE TITLE
アンケートの自由解答欄の背景色

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#100]
<img width="168" alt="cheese_academy_tokyo___ tokyo" src="https://user-images.githubusercontent.com/23730555/30358673-f7a61216-9880-11e7-88dd-d9237fef8a92.png">

**Comment by take-iwa** [comment]
選択肢の背景も白なので自由欄も白で、そして、入力文字色も選択肢と同じ色にして固定としてください。

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。
