### ISSUE TITLE
さらに表示をクリックしてもさらに表示されない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#104]
画像のさらに表示をクリックしてもさらに表示されない
![2017-09-15 20 28 25](https://user-images.githubusercontent.com/17405609/30480412-904aa6d8-9a54-11e7-8f41-bcb977c73391.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。
