### ISSUE TITLE
パスワード再設定メール

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#106]
再設定先のURLを追加してください。

<img width="287" alt="_2017-09-19_10_07_48" src="https://user-images.githubusercontent.com/23730555/30571418-887769fc-9d22-11e7-8bfe-b5df8aa1742b.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov こちらのURLに設定しても最初のログイン画面に遷移と思うので、
http://app.chapport.com/#/password-recovery/enter-code

例えば、こちらではいかがでしょうか？
http://chapport.com/enter-code.html?email=<ユーザーのメールアドレス>


メール文章としては、
```
<?php echo user_name ;?>様

パスワードの再送信依頼有難うございます。
パスワード再設定用のコードを送付致します
コードNo:【<?php echo 再設定コード?>】

再設定コード入力ページをお開きの場合は、
そちらからコードを入力しパスワードを再設定下さい。

閉じてしまわれた場合は、こちらのページよりお願いいたします。
http://chapport.com/enter-code.html?email=<?php echo user_mail; ?>

不明点などございましたら、お気軽にお問い合わせください。
=============================================
CHAPPORT事業部
カスタマーサポート
03-6447-4321
info@chapport.com
============================================
```

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
