### ISSUE TITLE
サイト管理者間で既読を共有したい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#107]
例えば、サイト管理者が複数人(Aさん,Bさん)いた場合、
お客さんのメッセージをAさんが読んだ場合、
Bさん側でも既読となるように、

**Comment by alexeypolitov** [comment]
@take-iwa こちらはロジックに合ってないです。ユーザーはそれぞれ自分「既読」ステータスを持ってます。

**Comment by tomoyuki1110** [comment]
こちらですが、既読を共有化できないでしょうか？
チームでやる場合、そっちのほうがわかりやすいかなと思ってまして。
