### ISSUE TITLE
マスタ管理画面：プラン追加後、決定、もう一度編集すると、ボットなどのボタンがOnしているものがOFFになっている。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#108]
管理画面：プラン追加後、決定編集すると、ぼっとなどのボタンがOnしているものがOFFになっている。

⇒そもそもONのものはONにOFFのものはOFFにお願いたします。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 確認しました。問題なかったです。プライベートモードでご確認ください
