### ISSUE TITLE
さらに表示をタップしても動かない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#109]
![screenshot_20170919-223101](https://user-images.githubusercontent.com/17405609/30594814-59e7c38a-9d8a-11e7-9ce9-19edf3bc7004.png)

プライベートモードで行ってます。
タップしても無反応でした。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。ご確認ください
