### ISSUE TITLE
アンケートのタイトルが何度もでるトラブルがまた発生している

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#110]
![screenshot_20170919-223503](https://user-images.githubusercontent.com/17405609/30595066-1216a53e-9d8b-11e7-94bd-93f2d85baa8e.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa こちらのフローを教えていただけますか？それとも動画をいただけますか？こちらですと問題発生できないです

**Comment by take-iwa** [comment]
@alexeypolitov すみません。大岩の方でも再現できず。
@tomoyuki1110 手順などありますでしょうか？

**Comment by tomoyuki1110** [comment]
とりあえず、出現したのは
スマートフォンで、

一回目アクセス(このときはアンケート書き込み)
一度閉じて、20分程度経った後もう一度アクセス
したら上の様に出ました。

今、自分でやっても確かに出てこないのでもう一度確認します。

**Comment by tomoyuki1110** [comment]
いまやったらたしかに出ないですね。一旦クローズします。
