### ISSUE TITLE
設定＞スケジュール　現在ステータスのオン/オフ表示を逆にして欲しい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#14]
ステータスがONの時は、表示も「オン」にする。
できれば、オン/オフでボタンの色も変わるとわかりやすい。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov ボタンの色はいいのですが、on/offの表示切り替えが修正されていないように思います。

<img width="1052" alt="_2017-06-15_14_16_20" src="https://user-images.githubusercontent.com/23730555/27166462-c324adfa-51d5-11e7-9267-bf4a95d4a525.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
合ってます。問題ありません。
