### ISSUE TITLE
設定＞スケジュール　時間設定を入力しやすいように変更

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#15]
24時間表示なのはわかるんですが、最初に0, 1, 2以外を入力できないということに気づくのに時間がかかった。時間設定で最初の入力で3~9の場合、頭の「０」を自動補完してほしい。
あるいは、ドロップボックスでも良い。現状だと29時とかも入力できてしまうので。

また、09:00~18:00 のように開始・終了時間の間に「〜」が入れてあるとわかりやすい。

**Comment by alexeypolitov** [comment]
@take-iwa dropdownで設定できるように変更すればいいですか？ここは宮本さんにこういう風に変更するのかご確認ください

**Comment by take-iwa** [comment]
相談の結果、dropdownでお願いします。↓みたいに「時」と「分」が別々になると思いますが。。。すみません。

![default](https://user-images.githubusercontent.com/23730555/27166708-946b0f20-51d7-11e7-8fbc-9fc4ffe8f0e1.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
確認しました、完璧です。
