### ISSUE TITLE
設定＞自動メッセージ　有効/無効の切り替え

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#16]
「表示/非表示」でなく、「有効/無効」の方がわかりやすい。
スライダーの色も変わるとより親切。

それから、最初の一覧表示でも「有効/無効」の切り替えができると便利だと思います。

**Comment by alexeypolitov** [comment]
> 「表示/非表示」でなく、「有効/無効」の方がわかりやすい。
> スライダーの色も変わるとより親切。

@take-iwa 承知しました。

> それから、最初の一覧表示でも「有効/無効」の切り替えができると便利だと思います。

こちらはちょっと大変です

**Comment by alexeypolitov** [comment]
>「表示/非表示」でなく、「有効/無効」の方がわかりやすい。
> スライダーの色も変わるとより親切。

@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
完璧です。

↓は、対応不要なので、クローズします。
>それから、最初の一覧表示でも「有効/無効」の切り替えができると便利だと思います。
