### ISSUE TITLE
設定＞自動メッセージ　アクションの「GotoOffline」が動かない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#17]
Go to Offlineの動作が確認できなかった。
ユーザー側で時間経ってもオフライン表示ならない？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov オフラインになるのを確認しました。オフラインというより、チャポートが非表示になるのですね。

気になったのは、指定時間経った時にチャット画面を開いていないと非表示にならない点です。

そして、追加で申し訳ありませんが、日本語化対応お願いします。
"GotoOffline"　⇒　「チャポートを非表示にする」

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
確認しました。OKです。
