### ISSUE TITLE
設定＞自動メッセージ　アクション「お問い合わせフォームを送る」が動かない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#18]
アクションの「お問い合わせフォームを送る」の動作が確認できなかった。
ユーザー側でお問い合わせフォームが開けばOK?

**Comment by alexeypolitov** [comment]
@take-iwa こちらでリンクを送るだけです

**Comment by take-iwa** [comment]
内容にURLを入力しておけばいいのでしょうか？
入力しましたが、ユーザー側に何も届きません。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 入力したURL届きました。こちら、リンク先にクリックで飛べるようにできますでしょうか？

**Comment by alexeypolitov** [comment]
> リンク先にクリック
こちらはどういう意味ですか？

**Comment by take-iwa** [comment]
@alexeypolitov すみません。URLがリンク化してなかったということです。
改めて、確認したところ、長いURLだとリンクにならないです。
#31 の件と似てるかもしれませんが、確認していただけますか？
<img width="457" alt="2017-08-01 14 55 30" src="https://user-images.githubusercontent.com/23730555/28811430-14f8ea4c-76ca-11e7-8348-de4eb2348765.png">

**Comment by tomoyuki1110** [comment]
普通のチャットもそうだが、
最初に日本語を入れて、リンクをいれると全体がリンク化する。

日本語を入れた後、スペースを入れたらリンク化しないように

**Comment by tomoyuki1110** [comment]
![2017-08-15 15 20 37](https://user-images.githubusercontent.com/17405609/29304349-70610c76-81cd-11e7-9227-24c141f74df4.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認下さい
