### ISSUE TITLE
設定＞自動メッセージ　「アカウント状態:チャット受付中がいる/いない」 や 「条件:オペレーターオフライン」が動かない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#19]
アカウント状態：チャット受付中がいる/いない　や　条件：オペレーターオフライン
どういう状態、条件で発生するのかわからず、確認できなかった。

マスター側のブラウザを閉じてやってみたが、何も起きず。

**Comment by alexeypolitov** [comment]
@take-iwa 他のところでブラウザーやアプリは起動中であればオンラインと判断されます

**Comment by take-iwa** [comment]
メッセージ届きました。OKです。クローズします。
