### ISSUE TITLE
設定＞自動メッセージ　条件を選択しない状態で登録できてしまう

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#20]
条件で追加ボタンを押し、条件未選択のままでも登録できてしまう。
　・デフォルトの設定を入れておく
　・未選択の条件項目を自動削除
　・未選択の場合は警告を出す
などの対応が必要か

**Comment by alexeypolitov** [comment]
@take-iwa こちらは追加として対応できます

**Comment by take-iwa** [comment]
本番環境で確認したところ、条件追加時にデフォルトの設定が入っていました。
こちらはクローズします。
