### ISSUE TITLE
設定＞自動メッセージ　キャンセルボタンは、保存ボタンの横に移動

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#21]
上にあった方が最初に間違った場合にキャンセルしやすいが、保存ボタンと並んでいるようが自然かと。

それから、自動メッセージ追加画面からグロナビの「設定」押すと、上の「キャンセル」が残ったままになる。

**Comment by alexeypolitov** [comment]
@take-iwa 他の画面でもキャンセルは上であります。ここは全てのシステムロジクを変更するのは大変です

**Comment by take-iwa** [comment]
確かに他の画面でも同じですね。クローズします。
