### ISSUE TITLE
設定＞デザイン　紹介文、オフライン紹介文設定の改行をユーザー側でも反映して欲しい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#22]
紹介文・オフライン紹介文で改行して設定してもユーザー側の表示では1行になってしまう。

設定で改行した場合、ユーザー表示側でも改行されるようにして欲しい。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 紹介文での改行は確認できました。

オフラインの文章も対応可能でしょうか？
<img width="750" alt="2017-06-15 15 53 45" src="https://user-images.githubusercontent.com/23730555/27168963-dca5aeac-51e2-11e7-9683-f15de173b063.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
バッチリです。
