### ISSUE TITLE
設定＞デザイン　「チャット用の写真」の設定が自動メッセージアイコン用が対象であることがわかりづらい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#24]
「チャット用の写真」設定が自動メッセージのアイコンが対象になることがわかりづらい。
「自動メッセージ用のアイコン」とかにしてくれると分かりよいかと。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。
