### ISSUE TITLE
設定＞デザイン　「オフラインのメッセージ」可能/不可能の動作が確認できない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#25]
「オフラインのメッセージ」が「可能」の場合に、どういう動作になるのかがわからず、確認できていません。
オフラインになった時にユーザーからメッセージが届けばOK?

**Comment by tomoyuki1110** [comment]
メッセージがどこに届くのでしょうか？

**Comment by tomoyuki1110** [comment]
届くためのメールアドレスはどこで設定しますか？

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 オフラインの時にメッセージは普通にチャットに届きます。ユーザー側だけ、表示が変わります

**Comment by take-iwa** [comment]
オフライン時のユーザーからのメッセージ送信確認できました。クローズします。
