### ISSUE TITLE
設定＞デザイン　カラー設定項目に紹介文の文字色も追加

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#26]
チャット領域の色を薄い色にすると紹介文が見づらくなるため。

**Comment by alexeypolitov** [comment]
@take-iwa ここまで増やすのは今の段階で厳しいです。以前から決まってる項目なので

**Comment by take-iwa** [comment]
@alexeypolitov 了解しました。決まっていたのですね。クローズします。
