### ISSUE TITLE
設定＞ボット　設定で上の階層に戻るボタンが欲しい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#27]
設定中に上の階層に行きたい場合があったため。
実はどこかにあるのでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 左サイドに「Back」確認しました。ありがとうございます。
