### ISSUE TITLE
マスターのチャット画面　自動メッセージの表示位置を右側にして欲しい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#28]
マスター(オペレーター)側のチャット画面を見ていて、ユーザーのメッセージと自動メッセージが左側に並んでいることに凄く違和感を感じました。

立場としては、自動メッセージもサービス提供側なので、右側に表示された方が自然かと思います。
ただ自分の発言ではないので、文字やバブルの色はそのままの方がいいかと思います。

**Comment by alexeypolitov** [comment]
@take-iwa こちらは以前から決まってるUIですので、今の段階で変更するのは厳しいです

**Comment by take-iwa** [comment]
了解しました。慣れれば不都合でもないと思うので、クローズいたします。
