### ISSUE TITLE
チャットで、httpやhttpsなどの時にリンクになる

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#30]
チャットで、httpやhttpsなどの時にリンクになる

現在はボットでもチャットでもリンク化しないのでリンクになるようにお願いします。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa どのリンクのことですか？

**Comment by tomoyuki1110** [comment]
チャットでのリンクです。
全体的な話した時の

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov こちらapp.chapport.comの方のチャット画面ではリンクになるのですが、お客さん側のチャット画面ではただの文字列になる場合があります。

加えて、リンクが途中までになっているので、修正お願いします。

app.chapport.comの方のチャット画面
<img width="845" alt="2017-07-24 18 17 42" src="https://user-images.githubusercontent.com/23730555/28516521-7aea276e-709c-11e7-801d-b1d7a09811e3.png">

お客さん側のチャット画面
<img width="338" alt="2017-07-24 18 17 54" src="https://user-images.githubusercontent.com/23730555/28516531-86814666-709c-11e7-8456-6bd28f10729c.png">

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境で確認しましたが、気になる点があります。
一度の入力でURLだけならOKかと思いましたが、文字＋URLを一度に送ると文字部分も含まれてしまいます。
<img width="318" alt="2017-08-06 4 42 36" src="https://user-images.githubusercontent.com/23730555/28998279-e75d9948-7a61-11e7-8d5f-281da898c2e0.png">

**Comment by tomoyuki1110** [comment]
http://up-t.jp  あいうえおなら問題ないですが、
あいうえお　http://up-t.jp　の場合はつながってしまいます。
直ってないようです

**Comment by tomoyuki1110** [comment]
![2017-08-15 09 32 37](https://user-images.githubusercontent.com/17405609/29297543-c86da928-819c-11e7-9a0f-20b29b6e6ddb.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認下さい
