### ISSUE TITLE
ボットの返答で文字、リンク、画像を入れられるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#31]
ボットの返答で文字、リンク、画像を入れて
改行などもできるように

**Comment by tomoyuki1110** [comment]
今だと改行しても行間をあけても
変わらなくなります。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa リンクは対応できますが、画像は厳しいです

**Comment by tomoyuki1110** [comment]
ここはなんとか対応したいが難しいですか？

**Comment by tomoyuki1110** [comment]
リンクと、改行などの対応はお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 改行確認しました。
リンクはURLが表示されるだけですが、クリックでリンク先に飛ぶようにするのは難しいでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov こちらも#30と同じですが、お客さん側ではリンクにならず、app.chapport.comのチャット画面ではリンクになるURLが途中までになっています。
<img width="398" alt="2017-07-24 18 24 19" src="https://user-images.githubusercontent.com/23730555/28516774-5c50a084-709d-11e7-9b6f-b1107b54988d.png">
<img width="324" alt="2017-07-24 18 22 15" src="https://user-images.githubusercontent.com/23730555/28516776-5d94fa30-709d-11e7-8bdf-879355e0295c.png">

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境で見ました。
リンクになってないように思います。また確認お願いします。

<img width="309" alt="2017-08-06 4 49 07" src="https://user-images.githubusercontent.com/23730555/28998319-a5847df6-7a62-11e7-915b-550003eba1c2.png">
