### ISSUE TITLE
ボット返答後キャンセルしないで次の質問をいれようとすると画面がおかしくなる

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#32]

**Comment by tomoyuki1110** [comment]
![screenshot_20170528-002958](https://cloud.githubusercontent.com/assets/17405609/26522483/00bb459a-433d-11e7-9c80-eee969fcaede.png)

参照画像

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
キャンセルしないで次の質問入力しても表示問題ありません。OKです。
