### ISSUE TITLE
pdfやwordなどのファイルアップロード時にイラストが出てこない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#33]
画像以外のときはファイルっぽい画像をイラストでだすように

現在は添付の画像のようになる
![screenshot_20170528-004006](https://cloud.githubusercontent.com/assets/17405609/26522574/7684054a-433e-11e7-8ad8-0d02abe19a08.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov @tomoyuki1110  pdf、gif、png、jpgでのアップロード&画像表示確認しました。
svgはアップロードできますが、表示できないですね。あまり使われないと思いますが・・・。

ちなみにチャットに画像が表示されるのはjpg形式だけで、他は以下のような表示になります。

![2017-06-15 17 42 47](https://user-images.githubusercontent.com/23730555/27173239-f373e3f0-51f2-11e7-89ae-0f8f46b9ca8a.png)

**Comment by take-iwa** [comment]
@alexeypolitov ２点ほど相談です。

1. wordやexcel（docx、xlsxなどの形式）は選べないようになってますが、こちらもアップロードできるように対応お願いします。

2. チャットに表示されるファイル名をアップロードした元のファイル名にできますでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 
1. word, excelのアップロードとダウンロードできること。
2. チャット画面でのファイル名の保持
確認しました。ありがとうございます。

ただ、もう一点だけ。
ファイルをダウンロードした際のファイル名も同じものにしてもらえないでしょうか？
↓アップしたファイル名
<img width="473" alt="2017-07-24 18 35 29" src="https://user-images.githubusercontent.com/23730555/28517300-e86169b8-709e-11e7-8c47-b2f81ee9f066.png">
↓ダウンロードしたファイル名
<img width="381" alt="2017-07-24 18 32 11" src="https://user-images.githubusercontent.com/23730555/28517267-ce1660e0-709e-11e7-8a35-43813c04ab9e.png">

**Comment by tomoyuki1110** [comment]
OK
