### ISSUE TITLE
ベーシックプランとプロフェッショナルプランの違い

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#36]
デフォルトはベーシックプラン

ベーシックプランとプロフェッショナルプランの違いは

BOTQ&Aを使えるかどうかという形にいたします。

**Comment by tomoyuki1110** [comment]
ベーシックプランでは人工知能BOTのリンクはあるが、
クリックしたらプロフェッショナルプランにお申込み下さい

と書いて下さい。

**Comment by tomoyuki1110** [comment]
月額支払
６ヶ月支払い
１２ヶ月支払い

を出来るようにしたいです。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 こちらは以前話した通り追加でよろしいですか

**Comment by tomoyuki1110** [comment]
はい。
プランはベーシックプランとプロフェッショナルプランのみ

ベーシックプランはQ&Aなどのボットシステムを使えない
プロフェッショナルプランは全て使える。

月額支払は
六ヶ月先払い
１２ヶ月先払いができるように

です。

**Comment by tomoyuki1110** [comment]
ベーシックプランでも、フォームが選べてしまうバグ

**Comment by alexeypolitov** [comment]
@tomoyuki1110 修正しました。ご確認下さい

**Comment by tomoyuki1110** [comment]
プランがみれないです

**Comment by alexeypolitov** [comment]
@tomoyuki1110 どういう感じで見れないですか？

<img width="959" alt="screen shot 2017-08-18 at 20 06 09" src="https://user-images.githubusercontent.com/3468058/29456473-b85fefda-8450-11e7-8f6b-894019cce030.png">

**Comment by tomoyuki1110** [comment]
真っ白になります。
![2017-08-18 20 11 05](https://user-images.githubusercontent.com/17405609/29456618-7686490a-8451-11e7-81f9-b7fef114d30c.png)

こちらプライベートモードです

**Comment by alexeypolitov** [comment]
@tomoyuki1110 アカウントの問題かもしれないです。ipassを教えてください

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 確認しました。
プランの内容は、adminで変更できるのも確認しました。

こちらですが、オーナーが支払い期間（月額支払、６ヶ月支払い、１２ヶ月支払い）を選ぶのはここでしょうか？ここは、どこで編集できますか？
<img width="238" alt="_2017-08-24_15_30_07" src="https://user-images.githubusercontent.com/23730555/29652644-5b611fda-88e1-11e7-9af3-e209454a531f.png">

それとクレカの場合は、どこで選べますか？
<img width="190" alt="_2017-08-24_15_30_12" src="https://user-images.githubusercontent.com/23730555/29652669-82b92b18-88e1-11e7-969a-cd94542d0ea5.png">

**Comment by take-iwa** [comment]
@alexeypolitov 選択するときに出てくるのですね。すみません。

現在プランのまま、支払い期間を変える場合は、どうしたら良いですか？

**Comment by alexeypolitov** [comment]
@take-iwa 以前からそうなってます。途中までプランを変更したらそのまま一ヶ月分を請求されます
