### ISSUE TITLE
チャットの改行などができるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#37]
チャットの改行などができるように

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov チャット画面では改行できてますが、オペレーター画面で改行できていないようです。
修正お願いします。↓の画像で左：チャット画面、右：オペレーター画面です。

<img width="837" alt="2017-06-15 18 24 52" src="https://user-images.githubusercontent.com/23730555/27174734-1542d6bc-51f8-11e7-9d91-c33d590e1ecf.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
確認しました！
