### ISSUE TITLE
ユーザー画面　Chatpportアイコンが隠れる

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#39]
試しに入れたページでページ幅が狭い時にアイコンが後ろに回ってしまった。
ページのコーディングのせいですが、なんとかならないでしょうか？
http://iwanko.sakura.ne.jp/

<img width="307" alt="2017-05-30 17 58 31" src="https://cloud.githubusercontent.com/assets/23730555/26575898/fdafc020-4561-11e7-84de-7aa9ffc2864e.png">

**Comment by tomoyuki1110** [comment]
これは必ずボタンが一番上になるようアレックスに設定してもらってください

**Comment by tomoyuki1110** [comment]
これは早急な修正必要です

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 大岩が使ってるスライダーが悪いのだと思うのですが、まだアイコンが裏に回りますね・・・。
確認してるのが、
http://iwanko.sakura.ne.jp/test/
で、スライダーで使っているのが、コレです。
http://flexslider.woothemes.com/
もし、cssの設定的にどうしてもそうなるとかならば、閉じます。

<img width="483" alt="2017-07-24 20 18 28" src="https://user-images.githubusercontent.com/23730555/28521151-4eb648ba-70ad-11e7-8e67-85b3a21d6e71.png">

**Comment by tomoyuki1110** [comment]
大岩くん。
これは必ず、上になるように作ってもらって下さい。

**Comment by tomoyuki1110** [comment]
またバグが出たら伝えます。
