### ISSUE TITLE
マスター画面　請求先の登録できない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#40]
必須入力はしていますが、プランを更新するボタンを押しても反応しません。
<img width="605" alt="2017-05-30 16 11 21" src="https://cloud.githubusercontent.com/assets/23730555/26576678/b201b1b2-4564-11e7-90ee-309903d85d32.png">

**Comment by take-iwa** [comment]
上は、無料登録した後に表示される「請求先情報を登録してください」から入力しようとした場合です。

オーナー画面のメニューから「プラン」でベーシックプランを選んだ時は、登録できました。

**Comment by alexeypolitov** [comment]
@take-iwa 確認しましたが、問題は発生してないです。可能であれば動画を撮っていただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov すみません、今しがた確認したら確かに問題なく登録できました。勘違いだったようです。閉じます。
