### ISSUE TITLE
アカウント作成できない場合がある

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#41]
自分が持っているhotmailのアドレスで登録しようとしたところ、アカウント作れませんでした。
「Plan.NotFound」
本番のページでです。
<img width="584" alt="2017-05-30 18 48 21" src="https://cloud.githubusercontent.com/assets/23730555/26577854/b79aebd0-4568-11e7-8ce3-c2a238b43ad2.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
問題なく登録できました。OKです。
