### ISSUE TITLE
マスター画面＞管理者＞招待メール　開発環境のURLが送られてくる

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#42]
本番環境からチャポートに登録のない人への招待メールを送った場合、メールに記載されたURLが開発環境のものだと思います。
<img width="399" alt="2017-05-30 18 53 07" src="https://cloud.githubusercontent.com/assets/23730555/26578092/7fccc088-4569-11e7-8531-6050afb42dfe.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 招待メールの送信って時間かかりますか？招待してから１時間ほど待ってますが、メールが届きません。

**Comment by alexeypolitov** [comment]
@take-iwa ２分以内で送信されてます。もう一回試していただけますか？それから誰に何時に共有したのか教えてください。それでDBで調べられます。又は迷惑メールに入ってる可能性もあります

**Comment by take-iwa** [comment]
@alexeypolitov こちらに送りましたが、やはりきませんね。迷惑メールフォルダにも入ってないです。
h.ooiwa@maruig.co.jp　に今日8/1の15:25に招待送りました。

**Comment by tomoyuki1110** [comment]
メールは来たが文章がおかしい
タイトル：◯◯様よりChapportのご招待が来ました

文章
このメッセージはCHAPPORTのサービス登録システムより自動
送信されています。お心当たりのない場合は、誠にお手数ですが、
本メールへの返信にてご連絡ください。
―――――――――――――――――――――――――――――――――――
◯◯様より、CHAPPORT(チャポート)への招待がありました。
こちらのリンクより新規登録をお願いいたします。
http://chapport.com/register.html

===================================================
丸井織物株式会社
Chapport事業部
0120-86-4321
info@chapport.com
===================================================

◯◯には名前が自動ではいるようにおねがいいたします

**Comment by take-iwa** [comment]
確認しました。okです.
<img width="525" alt="2017-08-24 15 35 30" src="https://user-images.githubusercontent.com/23730555/29652768-ef9215e2-88e1-11e7-89ae-682b87d193ab.png">
