### ISSUE TITLE
パスワードリセットでエラーが出る

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#43]
パスワードリセットしようとしたところ、以下のエラーが出た。
いや、正確にはまだ登録していなかったはずなんですが、すでにアカウントがあった。

<img width="591" alt="2017-05-30 18 57 20" src="https://cloud.githubusercontent.com/assets/23730555/26578289/2f45dffe-456a-11e7-9a8d-8d8f877ccdcf.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
リセットできました。OKです。
