### ISSUE TITLE
ユーザー画面＞ボット回答　文言の変更とボタンの追加

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#48]
１）「オペレーターへメッセージを送信します」
　　　　↓文言変更
　　「直接オペレーターに質問したい場合は、こちらをクリックしてください」

２）ボット回答の方には
　　「表示する」ボタンを追加

<img width="354" alt="_2017-07-19_16_48_48" src="https://user-images.githubusercontent.com/23730555/28356273-70476072-6ca2-11e7-9e89-d55321c7bcae.png">

**Comment by take-iwa** [comment]
加えて、ボットの回答には、「Q」と「A」をつけてください。
ex)
Q. チーズとは？
A. http://・・・・・・

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境で文言変更とボタンの追加確認しました。

**Comment by tomoyuki1110** [comment]
QとAがついてないです。それ以外はOkです

**Comment by tomoyuki1110** [comment]
![2017-08-15 23 45 03](https://user-images.githubusercontent.com/17405609/29320943-d1d98168-8213-11e7-85c5-0e8f29cf42fb.png)
