### ISSUE TITLE
マスター画面＞設定＞ボット　ファイル添付対応

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#49]
ボットの回答で画像表示やファイルをアップできるように
ボットの設定の時に画像やcsvファイルなどをアップロードできるようにしてください。

そして、それをユーザーがダウンロードできるように。

**Comment by alexeypolitov** [comment]
@take-iwa 対応しました。開発環境でご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境で確認できました。
