### ISSUE TITLE
マスター画面＞設定＞ボット　日本語化対応

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#50]
Upload answers from CSV file
↓
回答をCSVファイルでアップロード

If there is no answer in the list  ┬Send message to operator
　　　　　　　　　　　　　　  └Nothing
↓
リストに回答がなかった場合、┬オペレーターにメッセージを送る
 　　　　　　　　　　　　　  └何もしない

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境で確認できました。
