### ISSUE TITLE
マスター画面＞設定＞デザイン　カラー設定をセットで選べるようにする

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#58]
カラー設定は、それぞれ個別に自由に設定できるようになっていますが、
その他に全部のカラー設定をセットでいくつか選べるようにする。

<s>選択できるカラーセットは、後ほどアップします。</s>

**Comment by take-iwa** [comment]
@alexeypolitov すみません。データ準備できていないので、明日確認します。

**Comment by take-iwa** [comment]
チャット枠デザイン変更されてから、確認します。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 本番で変更しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 各所カラー変更できること確認しました。
タイトルバーや送信ボタンの色は固定ですか？

プロフィール編集やメッセージ送信、戻るのアイコン設定は無くなりますよね？
削除してください。

その上で、テーマ設定のフォーマットください。

**Comment by alexeypolitov** [comment]
@take-iwa 
> タイトルバーや送信ボタンの色は固定ですか？

以前のデザインでも変更する機能はなかったので、今回のもなしです。今回デザインのみの依頼でした。

> プロフィール編集やメッセージ送信、戻るのアイコン設定は無くなりますよね？
> 削除してください。

削除します。

> その上で、テーマ設定のフォーマットください。

まとめます。

**Comment by alexeypolitov** [comment]
@take-iwa 設定のフォーマットはこちらです。

```
{"button_normal_color":"#0C8016","button_alert_color":"#0C8016","operator_message_background_color":"#4DA3FF","operator_message_text_color":"#532A02","user_message_background_color":"#4DA3FF","user_message_text_color":"#532A02","chat_background_color":"#0C8016","input_message_color":"#415A3B","input_description_text_color":"#52F04D","forms_text_color":"#F3469F","placeholder_color":"#000775","forms_background_color":"#2F8655","nick_text_color":"#A82024","link_file_color":"#B3C787"}
```

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 開発環境では変更でいていること確認できました。
テーマの設定ですが、DBのchapport.design_templatesに登録すればいいのでしょうか？
フォーマットのjsonは'content'に入れるとして、最後のimage_urlはどこの画像が対象でしょうか？

**Comment by take-iwa** [comment]
@alexeypolitov ひとまずテーマ`初期設定`です。
[tema_初期設定.js.zip](https://github.com/DecodeLLC/chapport-admin-web/files/1316685/tema_.js.zip)

**Comment by take-iwa** [comment]
DBのchapport.design_templatesにタイトル＆JSONを追加するだけ
こちらで追加する。
