### ISSUE TITLE
マスター＞チャット画面　発言した人の名前が出ない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#59]
お客さん側のチャット画面には名前が表示されるのですが、
マスター画面のチャットには表示さえれない。
iOS版・andoroid版も同様です。

↓お客さん側
<img width="342" alt="2017-07-24 21 01 03" src="https://user-images.githubusercontent.com/23730555/28522667-efd0d28c-70b3-11e7-8b64-7d4038a20989.png">

↓マスター・オペレーター側web
<img width="880" alt="2017-07-24 21 00 54" src="https://user-images.githubusercontent.com/23730555/28522690-ffc1fc84-70b3-11e7-90f2-6cb01ef91852.png">

↓iOS
![img_0010 2](https://user-images.githubusercontent.com/23730555/28522715-17f8a21c-70b4-11e7-8f5b-7e6bb5dc266b.PNG)

↓Android版
![clip_now_20170724_210447](https://user-images.githubusercontent.com/23730555/28522745-4036c2c2-70b4-11e7-850c-536ef711ddcc.png)

**Comment by tomoyuki1110** [comment]
本番OK
