### ISSUE TITLE
銀行振込のメール

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#61]
メール文章がおかしいので、
お渡しした文章を入れてください。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 こちらはいかがですか？

**Comment by take-iwa** [comment]
@alexeypolitov 
名前と口座情報が足りないです。

<img width="377" alt="2017-08-23 16 11 31" src="https://user-images.githubusercontent.com/23730555/29603121-e5e803fe-881d-11e7-92b8-106f71b5e736.png">

念のため、メール文章も置いておきます。
[chapport_mail_text.txt](https://github.com/DecodeLLC/chapport-admin-web/files/1244491/chapport_mail_text.txt)

**Comment by alexeypolitov** [comment]
![screen shot 2017-08-23 at 2 17 32 pm](https://user-images.githubusercontent.com/3468058/29603323-be5c521c-881e-11e7-8e67-59a447e99391.png)
@take-iwa 管理画面でちゃんと設定されてないです

**Comment by take-iwa** [comment]
@alexeypolitov ありがとうございます。設定いたしました。
あとすみません。
メールの件名が「共有依頼」になっていますが、「ご利用料金請求のご案内」でお願いします。

**Comment by take-iwa** [comment]
@alexeypolitov メールの件名リストです。

feedback ：【Chapport】問い合わせ
invite：【Chapport】チャポートへの招待が届いております
bank payment created：【Chapport】ご利用料金請求のご案内
payment failed：【Chapport】ご利用料金の入金が確認できておりません
payment success：【Chapport】ご利用料金の入金を確認いたしました
restore code：【Chapport】パスワード再設定コードのご案内

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
