### ISSUE TITLE
ボットのところの設定が出てきません。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#62]
自分の設定だとボットの設定が出てきません。プランはプロフェッショナルプランを選んでいます。
![2017-07-29 21 14 04](https://user-images.githubusercontent.com/17405609/28744774-03865eb2-74a3-11e7-9131-3e73abd89049.png)

ID：mediaship.com@gmail.com
PASS:541110

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。開発環境でご確認ください。

**Comment by take-iwa** [comment]
開発環境では、設定が出ること確認できました。
@alexeypolitov "Q&A Bot"以外にカテゴリを増やすことはできますか？
