### ISSUE TITLE
下記画像の◯のところも色変更できるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#68]
お願いします。
![2017-08-14 22 10 48](https://user-images.githubusercontent.com/17405609/29273127-f2186a6a-813d-11e7-89e0-66a6bdd264d7.png)

**Comment by tomoyuki1110** [comment]
添付のマークもお願いします。

**Comment by tomoyuki1110** [comment]
オペレーターの名前、ユーザの名前のところも変更できるようにお願いします。

**Comment by take-iwa** [comment]
@alexeypolitov 項目は足りていると思いますが、デザインの変更して保存しても全然チャット画面に反映されないです。
アカウント：h.ooiwa@maruiorimono / maruiorimono
SDK：http://iwanko.sakura.ne.jp/test/

**Comment by take-iwa** [comment]
すみません。#72とまとめます。
