### ISSUE TITLE
ボットでのキーワード検索について

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#71]
mediaship.com@gmail.com
541110

上記のDinate..jpのボットで

テキスタイルモール　に３つのカテゴリを入れている。

検索キーワードにテキスタイルモールとは

テキスタイルモール

テキスタイルモールについて

とつくっているが、テキスタイルモール　で全てが出て来る

部分一致で出てくるのはそれで問題はないが、

一番上には、テキスタイルモールについて　と入れた場合

テキスタイルモールについて　という完全一致が出て来るようにしてほしい。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 すみません。ロジクの意味あんまりわからないです。もっとわかりやすく説明していただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov @tomoyuki1110 おそらく直っていないです。
やりたいことは、
例えば、下の場合だと、
<img width="371" alt="_2017-08-24_16_05_55" src="https://user-images.githubusercontent.com/23730555/29654049-969b7c76-88e6-11e7-9e71-8ac5e27223e6.png">

「乳製品というのは・・・」で入力したとき、
<img width="359" alt="2017-08-24 16 05 21" src="https://user-images.githubusercontent.com/23730555/29654085-afb5f326-88e6-11e7-8e8c-b77dd34869a8.png">
「乳製品」で引っかかるのはOKなのですが、

「乳製品についてなんですが・・・」と入力されたときに
<img width="329" alt="_2017-08-24_16_05_41" src="https://user-images.githubusercontent.com/23730555/29654116-dd07c14c-88e6-11e7-9d42-ed0737b54764.png">
キーワードと一致する回答が優先的に上に表示されるようになればということだと思います。

**Comment by take-iwa** [comment]
それと、ボット回答を追加・編集しようとするとファイルがアップロードされていないと保存できません。
ファイルアップロードは必須項目ではないので、お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa ファイル保存バグを修正しました

**Comment by take-iwa** [comment]
@alexeypolitov 確認しようと思ったのですが、ボットの回答の新規登録・既存回答の編集ができないです。

**Comment by take-iwa** [comment]
@alexeypolitov あれ？できました。そして、ファイル保存バグの修正確認できました。
クローズします。
