### ISSUE TITLE
ボットやフォームの文字も変更できるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#72]
一律変更でもいいと思ってますが、変更できるようには刷る必要があるかと思います。
![2017-08-16 00 21 42](https://user-images.githubusercontent.com/17405609/29322698-571192a8-8219-11e7-949d-fb841aae57b6.png)
![Uploading スクリーンショット 2017-08-16 00.24.07.png…]()

**Comment by tomoyuki1110** [comment]
![2017-08-16 13 22 33](https://user-images.githubusercontent.com/17405609/29347239-291eb21e-8286-11e7-97ba-09f838044ce2.png)

**Comment by tomoyuki1110** [comment]
ここもです

**Comment by take-iwa** [comment]
@alexeypolitov デザインの項目は足りていると思いますが、デザインの変更して保存しても全然チャット画面に反映されないです。
アカウント：h.ooiwa@maruiorimono / maruiorimono
SDK：http://iwanko.sakura.ne.jp/test/

**Comment by take-iwa** [comment]
全て確認できたと思います。
