### ISSUE TITLE
アンケート後各アンケートの答えに対してコメントが入れられるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#73]
お願いします。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 ユーザーからのコメントですか？

**Comment by tomoyuki1110** [comment]
管理者からのコメントです。

例えば・・・・

アンケートで
Q1＝料金について
Q2＝他社の比較について

を選んだ時に、その説明がでてくるためのコメントをこちらで用意してでるようにするということです。

**Comment by tomoyuki1110** [comment]
Chamoの機能は既にそれがありますので、同じものを用意頼みます。
アンケートというよりも、必要なものをこちらで探せる機能として作っているので。
