### ISSUE TITLE
フォーム登録用のCSVが動いていない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#75]
CSVを入れているのに登録ができませｎ。
CSVはSlackに入れています。

**Comment by take-iwa** [comment]
@alexeypolitov ボットのcsvファイルアップロードのことですよね？
入力形式がわからなかったので、サンプルファイルをダウンロードして見たのですが、
内容がわかりません。確認お願いします。

ダウンロードしたファイルです。csv対応しておらず、zipにしてあります。
[example-categories.csv.zip](https://github.com/DecodeLLC/chapport-admin-web/files/1248222/example-categories.csv.zip)

**Comment by alexeypolitov** [comment]
@take-iwa ファイルフォーマットなど修正しました。ご確認ください
