### ISSUE TITLE
設定＞スケジュール　平日設定で土日が含まれている

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#77]
平日
毎日
カスタム

として、平日設定では、土日含まないようにお願いします。

**Comment by take-iwa** [comment]
@alexeypolitov 平日設定が合っているかは、土曜に確認して見ます。

選択項目に毎日を追加お願いします。

**Comment by take-iwa** [comment]
@alexeypolitov 
スケジュールの選択肢を３つにしていただけますか？
毎日
平日
カスタム

毎日は、文字通り土日を含む毎日
平日は、月〜金
カスタムは、今まで通りで。

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました
