### ISSUE TITLE
チャットフレーム枠の変更（追加要件）

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#78]
チャットフレーム枠の変更をお願いします

**Comment by alexeypolitov** [comment]
https://www.dropbox.com/sh/h00y7eq5sd5dioa/AACqnJLpvaZrN_Xa6vwavIMua?dl=0

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 本番で変更しました。ご確認ください。
