### ISSUE TITLE
常時SSL対応

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#79]
常時SSL対応したサイトにチャポートのタグを入れるとブロックされ表示されない。

ex) スタンプファクトリー　https://stampfactory.net/
chapportアカウント：
a.tada@maruig.com/atsushi10

chromeで出たエラー内容
`Mixed Content: The page at 'https://stampfactory.net/' was loaded over HTTPS, but requested an insecure script 'http://sdk.chapport.com/chapport.js'. This request has been blocked; the content must be served over HTTPS.`

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。サイトでwidgetのソースコードを更新してください

**Comment by take-iwa** [comment]
@alexeypolitov 表示できました。なぜかメッセージは遅れませんが。
