### ISSUE TITLE
アンケートが終わったときに、メッセージを送りたい。

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#80]
最後までアンケートを答えてくれた人にサンクスメッセージを送りたい。

「skip all」した人には、送らないようにする。

**Comment by alexeypolitov** [comment]
@take-iwa こちらの機能は今までなかったので、追加でやるのか、なしなので宮本さんに判断していただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 入れてください。
デフォルトの文章は、↓でお願いします。

ご協力ありがとうございました。
