### ISSUE TITLE
アンケート追加のときの紹介文とタイトルという文言が逆

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#81]
アンケートを追加するときの紹介文とタイトルが逆です。
ボックスはそのままで合っています。
<img width="198" alt="_2017-08-24_16_30_23" src="https://user-images.githubusercontent.com/23730555/29654823-b8fd773a-88e9-11e7-8d93-c8e8efefca00.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
