### ISSUE TITLE
日本語修正お願いします。

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#82]
①自動メッセージ　アクション
send form → アンケートを送る

<img width="380" alt="2017-08-24 16 38 24" src="https://user-images.githubusercontent.com/23730555/29656188-a22b31e6-88ee-11e7-90da-8a9e0c9d67f8.png">

②インプットプレスホルダ　→　入力欄デフォルト文
<img width="471" alt="2017-08-24 17 13 34" src="https://user-images.githubusercontent.com/23730555/29656537-b2a39da0-88ef-11e7-8ffe-30aa01058bc4.png">

③インプット　→　入力文章
<img width="390" alt="2017-08-24 18 28 52" src="https://user-images.githubusercontent.com/23730555/29659746-2a6f002c-88fa-11e7-84ca-40b4d4e39d4e.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました
