### ISSUE TITLE
デザインのチャットボタン、表示場所のバグ

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#83]
初めに左下に選んで保存。もう一度設定をしようと設定を見ると、なぜか左下ではなくて右下になっている。逆に右下を選んで保存。もう一度設定をしようと設定をして表示場所を見ると左下になっている。

右下を選んだ場合は、もう一度設定をクリックしても右下
その逆も同じでお願い致します

**Comment by alexeypolitov** [comment]
@tomoyuki1110 チャットのソースコードを更新しましたか？更新しないとバグが起きます。

**Comment by tomoyuki1110** [comment]
誰も変更してないようです。確認しました。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 本番で変更しました。ご確認ください。
