### ISSUE TITLE
料金請求の銀行振込メールに金額がない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#84]
<img width="184" alt="_2017-09-04_14_12_11" src="https://user-images.githubusercontent.com/23730555/30012506-37284e20-917b-11e7-99c3-316d60bc2cb5.png">

**Comment by alexeypolitov** [comment]
@take-iwa 追加しました

**Comment by take-iwa** [comment]
@alexeypolitov 都合の良い時に請求メール流していただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 請求金額入っているのですが、細かい指定しなくてすみませんでした。
こちら以下のように詳細に出していただけないでしょうか？

◯◯プラン使用料：◯◯円
消費税：◯◯円
ご請求金額合計：◯◯円

それと、振込先情報の改行がなくなっています。
設定通り、改行するようにお願いします。

`うさぎ様
こちらCHAPPORTカスタマーサポートです。
請求書の作成が完了いたしました。
下記の口座へ料金のご入金をお願いいたします。

請求金額：5000円


銀行名 : 楽天銀行 店番 : 第一営業支店（251） 口座番号 : 普通 : 7501851 口座名義 : 丸井織物　株式会社


`

**Comment by alexeypolitov** [comment]
@take-iwa 
> 消費税：<?php echo ; ?>円

chapport自体、消費税は対応してないですので、削除させていただきます。

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。
