### ISSUE TITLE
アンドロイドで名前をいれるときに上がってしまう。

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#85]
画像参照。
Iosでの確認は
![screenshot_20170911-161403](https://user-images.githubusercontent.com/17405609/30270308-1abf59ca-9727-11e7-98e4-5bcba0baedb0.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa こちらはios/androidでご確認していただいて、アンドロイドだと２つ端末でお願いします。それから問題がある端末名＆動画をアップください

**Comment by tomoyuki1110** [comment]
Android　EXPERIA　Z5

**Comment by tomoyuki1110** [comment]
AQUOS SH04-H
