### ISSUE TITLE
アイコンの画像のアップロードが出来ない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#86]
画像アップロードができなくなってます。
修正お願い致します。

**Comment by tomoyuki1110** [comment]
デザインアイコンなどのアップロード画像です

**Comment by alexeypolitov** [comment]
<img width="486" alt="screen shot 2017-09-12 at 13 24 29" src="https://user-images.githubusercontent.com/3468058/30308087-bb3e0360-97bd-11e7-900d-cbe5274683ba.png">

@tomoyuki1110 @take-iwa  普通にアップされてます

**Comment by tomoyuki1110** [comment]
こちらはアイコンの画像は他も含めてpngなどの画像でもいけました
修正お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。
