### ISSUE TITLE
マスタ管理画面で支払い待ちを支払い済みボタンを押しても支払い待ちのまま

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#88]
マスタ管理画面で支払い待ちを支払い済みボタンを押しても支払い待ちのまま

**Comment by tomoyuki1110** [comment]
![2017-09-12 01 44 10](https://user-images.githubusercontent.com/17405609/30286269-008ccec2-975c-11e7-8692-a0cbe364a8f9.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 ajaxですので、画面を更新したらフループのステータが変更されます。
<img width="1440" alt="screen shot 2017-09-12 at 13 43 59" src="https://user-images.githubusercontent.com/3468058/30308435-74007dea-97c0-11e7-8c3b-8cfb56ab64a5.png">
