### ISSUE TITLE
ご利用料金の入金案内メール

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/chapport-admin-web#91]
うさぎ？　になっています。

名前　様　になるようにお願い致します。

また文章を下記に変更お願い致します。

タイトル：【Chapport】ご利用料金の入金を確認致しました

◯◯様

いつも有難うございます。
Chapportカスタマーサポートでございます。

◯月分のご利用料金のご入金を確認致しました。
ご利用の方誠に有難うございます。

ご不明な点等ございましたら、いつでもご連絡下さい。
今後共宜しくお願い致します。
========================================
Chapportカスタマーサポート
info@chapport.com
0120-86-4321
========================================

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa こういうフォーマットの対応不可能です。大岩さんが作ってるフォーマットに変更してください

**Comment by take-iwa** [comment]
@alexeypolitov こちらでよろしいでしょうか？
```
/* 【Chapport】ご利用料金の入金を確認致しました */
<?php echo $data['nickname'] ; ?>様

いつも有難うございます。
Chapportカスタマーサポートでございます。

<?php echo ; ?>月分の利用料金の入金を確認いたしました。
ご利用の方誠に有難うございます。

ご不明な点等ございましたら、いつでもご連絡下さい。
今後共宜しくお願い致します。
=============================================
CHAPPORT(チャポート)カスタマーサポート
0120-86-4321
info@chapport.com
=============================================
```

**Comment by alexeypolitov** [comment]
@take-iwa ありがとうございます

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
<img width="180" alt="_ _yahoo_ 52 1" src="https://user-images.githubusercontent.com/23730555/30526057-999b6d0c-9c4e-11e7-90cd-923ce2bf9605.png">

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。

**Comment by take-iwa** [comment]
@alexeypolitov こちら自分の持っているアカウントだと払い切ってしまって請求がない状態なのですが、9月分の請求とか先に送れないでしょうか？
