### ISSUE TITLE
ボットでファイルのアップロードができない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#97]
<img width="223" alt="chapport" src="https://user-images.githubusercontent.com/23730555/30357733-41b4bab6-987b-11e7-8d2e-a83bcc4161ff.png">

テキストファイルはできました。
<img width="181" alt="chapport" src="https://user-images.githubusercontent.com/23730555/30357918-49d83b7c-987c-11e7-9762-07c0c349e3cb.png">

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。
