### ISSUE TITLE
adminのダッシュボードがchapport全体の数字でない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/chapport-admin-web#99]
ログインしたユーザーが管理するサイトの集計になっている。

<img width="606" alt="chapport" src="https://user-images.githubusercontent.com/23730555/30358527-f7719b18-987f-11e7-83ad-6a8f7a4a5856.png">

<img width="614" alt="chapport_admin" src="https://user-images.githubusercontent.com/23730555/30358550-1c0a3d36-9880-11e7-925d-962673178c49.png">

**Comment by alexeypolitov** [comment]
@take-iwa @tomoyuki1110 修正しました。ご確認ください。
